---
# Runs an ansible role
# Usage:
#   ansible-playbook ./run_role.yml -i "hostname," -e role=my_awesome_role
#
- hosts: all
  remote_user: root
  become: True
  gather_facts: True
  roles:
    - "{{role}}"
